### ISSUE TITLE
STM32F4 Discovery - unknown chip id! 0xe0042000

### ISSUE THREAD

**Issue by jpmzometa** [stlink-org/stlink#107]
Hi, i have a problem similar as #issue 64, but with a STM32F4-DISCOVERY. 

st-flash write build/ch.bin 0x8000000

2012-09-01T18:33:59 INFO src/stlink-usb.c: -- exit_dfu_mode
2012-09-01T18:33:59 INFO src/stlink-common.c: Loading device parameters....
2012-09-01T18:33:59 WARN src/stlink-common.c: unknown chip id! 0xe0042000
stlink_sram_flash() == -1

Any hints?

**Comment by joostrijneveld** [comment]
Thanks @latsku, that worked perfectly.

**Comment by erwincoumans** [comment]
@latsku yes, your 3 steps worked for me too. Thanks!

**Comment by ADARSHBU** [comment]
Hi Latsku,

Great buddy, those 3 steps works fine for me .... 
Thank you..

**Comment by vdudouyt** [comment]
@latsku thank you very much for your suggestion! This helped me as well.

**Comment by kont-noor** [comment]
Tried all suggestions but still get `WARN src/stlink-common.c: unknown chip id! 0xe0042000`

**Comment by ADARSHBU** [comment]
Hi,
Check the below link, that works fine for me.

https://github.com/texane/stlink/issues/107



On Tue, Sep 22, 2015 at 7:24 PM, Nickolay Kondratenko <
notifications@github.com> wrote:

> Tried all suggestions but still get WARN src/stlink-common.c: unknown
> chip id! 0xe0042000
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/texane/stlink/issues/107#issuecomment-142295944>.
>



-- 
Regard's
ADARSH B U

**Comment by kont-noor** [comment]
@ADARSHBU it's a link to the current page

**Comment by ADARSHBU** [comment]
@ Nickolay : Even I faced the same issue at the beginning of my work and
solved it by following  the procedure mentioned by Latsku.

*unknown chip id 0xe0042000*
This means either 1) you have bricked the ST-Link bridge chip (U2) somehow
- you'll need ST's own Windows utilities to fix that, or 2) you are trying
to flash the Discovery in ST-Link (SWD/JTAG) mode. Replace the CN3 jumper
if you're using the Discovery board!

Also, follow the instructions in the stlink readme *to the letter..*.
Simply going into GDB and calling "load whatever.elf" didn't work, you need
to

   1. start st-util
   2. load the elf file in GDB ("gdb fancyblink.elf")
   3. (gdb) load
   4. wait...
   5. (gdb) cont

and your code will start. *Don't *use *run* instead of *cont*, that doesn't
seem to work either. Unintuitive but there you go.


I would also like to suggest you to check with
1. Jumper Configuration
2. Have a look at: #62 <https://github.com/texane/stlink/issues/62>
3. Also flash does not work when CPU is in sleep mode

On Wed, Sep 23, 2015 at 2:48 PM, Nickolay Kondratenko <
notifications@github.com> wrote:

> @ADARSHBU <https://github.com/ADARSHBU> it's a link to the current page
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/texane/stlink/issues/107#issuecomment-142538816>.
>



-- 
Regard's
ADARSH B U

**Comment by ogzarm** [comment]
1.open Stm32 St-link utility application
2.Target>Settings  mode should be Connect Under Reset
3.Full erase chip
it is okey.

**Comment by polaroi8d** [comment]
@latsku im very new in stlink and boards, so sorry for the dumb question but, what does "1. Short the BOOT0 pin with VDD" really mean?

**Comment by latsku** [comment]
@polaroi8d Not a dump question at all.
Connect the BOOT0 pin with the VDD pin.

And the electronics slang part. Short comes from short circuit, which is connecting the pins with a wire or similar conductor.

**Comment by polaroi8d** [comment]
@latsku Okey, thanks for the answer, its woorking :)

**Comment by tcurdt** [comment]
So far I have just connected the `ST-LINK V2` (with no board connected) and then ran `st-util` which gave the `rc/stlink-common.c: unknown chip id! 0xe0042000` which let me here.

Now is this because there is no board connected?
Or is this about the `ST-LINKV2` itself?
Or what is it?

I still have to try the above instructions on how to fix this - but could someone try to explain what the problem actually is? I didn't get it from the above comments yet.

**Comment by tcurdt** [comment]
@xor-gate why the close without further explanation?

**Comment by xor-gate** [comment]
Because this issue dates back to 2011 and is kept alive by != author. Feel free to reopen a new detailed issue tested against stlink tools currently in master.

**Comment by joostrijneveld** [comment]
The comment by @ADARSHBU has proved to be valuable to me; I want to stress the fact that the CN3 pins need to be shorted.

Out of the box, discovery boards come with a shorter jumper on these pins, but one of our boards had somehow lost this jumper and it took a while to notice. When in doubt, look up a few photos of the relevant board and check if the same jumpers are in place on yours!

**Comment by afiskon** [comment]
For people who comes to this issue from Google. If you see an `unknown chip id! 0xe0042000` error this most likely means that you connected ST-Link pin SWDIO to the CLK pin of your STM32 board and vise versa (SWCLK on ST-Link to IO pin on the board). Just re-check the connection, it should be SWDIO -> IO and SWCLK -> CLK. This is exactly what happened to me.

**Comment by tcurdt** [comment]
@afiskon not sure about the "most likely" but it might be a cause

**Comment by hggq** [comment]
Thanks @latsku your 3 setup very good
