### ISSUE TITLE
[feature] macOS support

### ISSUE THREAD

**Issue by VIPQualityPost** [stlink-org/stlink#1331]
I know that macOS support was dropped previously for moving forward. 
I was wondering what the motivation for this was? 

I am happy to try and offer what little help I can to implement / test support for these devices on macOS (both Intel and Apple silicon). The newer v3-minie is a great choice for developing embedded hardware on mac (small, cheap, and with USB-C!) , and I use it frequently with platformIO but I would also like these command line tools and to be able to use an open-source driver :) Unfortunately, the minie shows up in device list of st-info, but is explicitly not supported for use (although I imagine the driver is not so different from the mac-supported STLINK V3-SET.
```
% st-info --probe
2023-08-30T13:54:33 WARN usb.c: skipping ST device : 0x483:0x3754)
Found 0 stlink programmers
```

**Comment by Nightwalker-87** [comment]
Please refer to #1269, #1280, #1296 and #1313 for more references.
The problem is rather the OS-implementation itself with it's increasing technical policies, changes and restrictions that force us to drop support as it obstructs the development of this toolset.
Further this is not very friendly with respect to versatile use of hardware-related open source tools in general.
