### ISSUE TITLE
Incorrect description

### ISSUE THREAD

**Issue by whitequark** [stlink-org/stlink#3]
As the utility now supports much more chips than the original STM32VLDISCOVERY, the one-line description at the top of repository page is incorrect. Maybe it should be replaced with "Programmer for STM32 over ST-Link SWD" or something like that (grammar may be incorrect).

**Comment by Nightwalker-87** [comment]
Yes, I understand what you mean. In fact this is misleading.
Looking at the [STMicroelectronics website for MCUs and MPUs](https://www.st.com/en/microcontrollers-microprocessors.html) and realising that we also support macOS and Windows since this ticket was created, we should replace `stm32 discovery line linux programmer` with `STM32 MCU programmer` to get everything right. @texane can you correct this as beeing the owner of this project? Thx.

**Comment by whitequark** [comment]
Why did you assign to me an issue I opened 8 years and 10 months ago?

**Comment by Nightwalker-87** [comment]
This was obviously a mistake in relation with the set label "needs/issuer-feedback", as I did not request anything from you here. Sorry for that. :-/

**Comment by Nightwalker-87** [comment]
@texane: Can you take action on this or is there a possibility to give write-access to this, so that I can fix it myself?

**Comment by Nightwalker-87** [comment]
Yes, I understand what you mean. In fact this is misleading.
Looking at the [STMicroelectronics website for MCUs and MPUs](https://www.st.com/en/microcontrollers-microprocessors.html) we should replace `stm32 discovery line linux programmer` with `Open source STM32 MCU programming toolset` to get everything right.

**Comment by Nightwalker-87** [comment]
The description of this project is now corrected what resolves this issue.
