### ISSUE TITLE
[macOS] Support for ST-Link-v1 in macOS High Sierra? (Kernel Extension)

### ISSUE THREAD

**Issue by PickRelated** [stlink-org/stlink#735]
Since El Capitain there were no new kexts. I would love to launch my STLink v1 on MacOS High Sierra. 

Could you please write one? Or may be you could help me out with doing it myself? I have never written kexts or software under MacOS before.

Thanks!

**Comment by PickRelated** [comment]
I think the problem might be with High Sierra itself because when I try to load kext I get this.
```
$ sudo kextutil -v /System/Library/Extensions/stlink_shield.kext

Defaulting to kernel file '/System/Library/Kernels/kernel'
Untrusted kexts are not allowed
Kext with invalid signature (-67062) denied: /Library/StagedExtensions/System/Library/Extensions/B100D010-6109-4259-BD2B-2A33C2518E76.kext
Bundle (/System/Library/Extensions/stlink_shield.kext) failed to validate, deleting: /Library/StagedExtensions/System/Library/Extensions/B100D010-6109-4259-BD2B-2A33C2518E76.kext
Unable to stage kext (/System/Library/Extensions/stlink_shield.kext) to secure location.
```

**Comment by PickRelated** [comment]
I have disabled SIP and the kext was successfully loaded. But `st-util` still has no luck with my STM32VLDiscovery.
```
$ st-util
st-util 1.4.0
2018-09-08T02:46:25 WARN usb.c: Stlink usb device found, but unable to claim (probably already in use?)
[!] send_recv send request failed: LIBUSB_ERROR_NOT_FOUND
[!] send_recv STLINK_DEBUG_RESETSYS
2018-09-08T02:46:25 INFO gdb-server.c: Chip ID is 00000000, Core ID is  00000000.
2018-09-08T02:46:25 INFO gdb-server.c: Listening at *:4242...
^C[!] send_recv send request failed: LIBUSB_ERROR_NOT_FOUND
[!] send_recv STLINK_DEBUG_RUNCORE
[!] send_recv send request failed: LIBUSB_ERROR_NOT_FOUND
[!] send_recv STLINK_JTAG_WRITEDEBUG_32BIT
```

**Comment by PickRelated** [comment]
Might also be helpful. When I try to trace the kext problems I get this.
```
$ sudo kextutil -t -n stlink_shield10_10.kext
Kext with invalid signatured (-67062) allowed: <OSKext 0x7ff7a8700a70 [0x7fff92302980]> { URL = "stlink_shield10_10.kext/ -- file:///Users/pin/rep/stlink/stlinkv1_macosx_driver/osx/", ID = "com.libusb.stlink_shield" }
Code Signing Failure: not code signed
Warnings:
    Personality CFBundleIdentifier differs from containing kext's (not necessarily a mistake, but rarely done):
        DeviceDriver
        InterfaceDriver
    Kext has no executable or compatible version, so it should not declare any OSBundleLibraries.

Warnings:
    Personality CFBundleIdentifier differs from containing kext's (not necessarily a mistake, but rarely done):
        DeviceDriver
        InterfaceDriver
    Kext has no executable or compatible version, so it should not declare any OSBundleLibraries.

stlink_shield10_10.kext appears to be loadable (including linkage for on-disk libraries).
```

**Comment by xor-gate** [comment]
I would recommend buying a v2 or v2-1 programmer. Stlink also doesn't support v1 anymore in their stlink utility if I'm correct. Just bring your v1 to the museum and spend 20 euro, then you are the man.

**Comment by PickRelated** [comment]
I have v2, but I am traveling and I have to program two devices at the same time for their communication. One STM32VLDiscovery is attached to st-link v2 and other STM32VLDiscovery I want to program by itself, not disconnecting a thousand wires from another board :(
I am sure if you just fix kext library versions or something - it will work. This kext simply has to overtake default mass storage driver as I understand.

**Comment by xor-gate** [comment]
I have no idea, not su much people use the stlink v1.

**Comment by Nightwalker-87** [comment]
Related to #852 .
As commented there we need a major update on this.
We seem to lack proper support for current macOS versions.

**Comment by Nightwalker-87** [comment]
We will be having problems relating kexts in future releases of macOS as these have been deprecated by Apple: https://developer.apple.com/de/support/kernel-extensions/

This implies the need for a new approach to ensure the same functionality currently present.

**Comment by Nightwalker-87** [comment]
Related to #574.

**Comment by Nightwalker-87** [comment]
Related to #574.

**Comment by Nightwalker-87** [comment]
We will be having problems regarding Kernel Extensions (kext) in future releases of macOS as these have been deprecated by Apple: https://developer.apple.com/de/support/kernel-extensions/

Against this background we will not provide a new kext for later macOS versions.
The above implies as well that we either need a new approach to ensure the same functionality currently present or as an alternative cease any support for the legacy ST-Link-v1 programmer in the `stlink` toolset.

Discussion on this topic is now open. Please have your say.

**Comment by Nightwalker-87** [comment]
I think this could possibly be a topic for you @chenguokai as you are a MacPorts maintainer. I can imagine that this will pop up at yours anyway - no matter what project, be it sooner or later... Maybe we can discuss and make up our minds together.

**Comment by chenguokai** [comment]
For now, I suggest a deprecation or a complete drop of stlinkv1 kext.

Apple has introduced SIP mechanism to macOS since 10.11, a kext without licenses signed by Apple can be such a pain to load.
In MacPorts, stlink is currently compiled without the old kext installed. The formula of Homebrew does almost the same thing.

But as I see that the writer said the kext is an codeless one, I will check tomorrow to see if there is any chance that this kext builds well on newer systems.

**Comment by Nightwalker-87** [comment]
> In MacPorts, stlink is currently compiled without the old kext installed. The formula of Homebrew does almost the same thing.

Ah, that is good to know, thx.

Maybe we can use the new "System Extension" format Apple propagates as a replacement for the old kext modules. I have not dealt with this yet, but if it is not too hard to implement, this could be an option. Should it be too much effort, we may drop support for the STlink-v1 on macOS.

**Comment by chenguokai** [comment]
Tested on my macOS 10.14.6, the source code builds well, but its load is prohibited by the system with the following logs:

`Kext with invalid signature (-67050) denied: /Library/StagedExtensions/Users/cgk/Downloads/stlink_shield 2020-04-10 11-39-10/Products/System/Library/Extensions/3D7187E2-15F5-45E7-BFB7-5BB63539049D.kext`
`Bundle (/Users/cgk/Downloads/stlink_shield 2020-04-10 11-39-10/Products/System/Library/Extensions/stlink_shield.kext) failed to validate, deleting: /Library/StagedExtensions/Users/cgk/Downloads/stlink_shield 2020-04-10 11-39-10/Products/System/Library/Extensions/3D7187E2-15F5-45E7-BFB7-5BB63539049D.kext`
`Unable to stage kext (/Users/cgk/Downloads/stlink_shield 2020-04-10 11-39-10/Products/System/Library/Extensions/stlink_shield.kext) to secure location.`
`Kext with invalid signature (-67050) denied: /Library/StagedExtensions/Users/cgk/Downloads/stlink_shield 2020-04-10 11-39-10/Products/System/Library/Extensions/B2288B91-0A94-4076-A713-C0CB5727FF18.kext`
`Bundle (/Users/cgk/Downloads/stlink_shield 2020-04-10 11-39-10/Products/System/Library/Extensions/stlink_shield.kext) failed to validate, deleting: /Library/StagedExtensions/Users/cgk/Downloads/stlink_shield 2020-04-10 11-39-10/Products/System/Library/Extensions/B2288B91-0A94-4076-A713-C0CB5727FF18.kext`
`Unable to stage kext (/Users/cgk/Downloads/stlink_shield 2020-04-10 11-39-10/Products/System/Library/Extensions/stlink_shield.kext) to secure location.`
`com.libusb.stlink_shield was unable to stage properly; failing.`

Errors are possibly triggered by the SIP, which prohibits unsigned kexts from loading.
For now, I can generate kexts for systems ranging from 10.9 to 10.15. No test can be performed by myself because I have neither ST Link v1 hardware nor a High Sierra system.

If the kext is fortunate enough to work on newer systems, I suggest maintaining a document about its support rather than installing by default.

**Comment by chenguokai** [comment]
After detailed search, I have the following findings:

It is a known problem to libusb [https://github.com/libusb/libusb/wiki/FAQ](https://github.com/libusb/libusb/wiki/FAQ) I would recommend trying unload kexts that match the ST Link v1. Volunteers needed to test. Other methods seem to be more tricky and destructive. I would not recommend modifying stock kexts or loading codeless kexts. The former one might cause boot failure, the latter one requires users to disable SIP as long as they do not own a kext develop license. Also I tried updateing the kext without SIP on, but no luck.

If the matches cannot be bypassed, a drop at least for newer systems can be expected.

**Comment by Nightwalker-87** [comment]
Well, SIP is not a problem for us (it should not be disabled completely BTW!) - we have documentation in our tutorial on how to keep it enabled and being able to load kexts at the same time. Trying it with unsigned kexts being blocked by SIP does not help any further - we now that this causes strange side effects (i would not like to investigate really).

**Comment by chenguokai** [comment]
@Nightwalker-87 Ever since macOS 10.14, it has been no longer possible to partially disable SIP, i.e. the tutorial does not apply to the latest two versions of macOS.

**Comment by Nightwalker-87** [comment]
Oh, I didn't realise that - Thank you. I will update our tutorial then.

**Comment by Nightwalker-87** [comment]
So what's the plan on how to proceed here? Would it be worth the efforts to write a kext for macOS 10.13 High Sierra, or shall we leave it? As far as I can read from our STlinkv1-Driver we currently support 10.6 - 10.10. Additionally there is a reference (https://github.com/stlink-org/stlink/issues/574#issuecomment-418996773) that the 10.10 kext is still usable on 10.13, so I assume it also runs on 10.12 and 10.11. If there is no change necessary in the module itself, we may think to simply modify/duplicate the codeless 10.10 kext for 10.11 to 10.13 (10.14, 10.15?) OR simplify the current one to be multi-version compatible. Further I'd propose to exclude the look into the future (deprecation of kexts) here in this issue. We may put that up on the agenda in a future release. It is not that urgent right now and we don't no exactly what the future brings to us. @chenguokai can you look at this again? Additionally we need someone with a mac and a STlink-v1 for testing.

**Comment by chenguokai** [comment]
Kexts are actually directories with a special structure. The codeless Kext used for STLink v1 has a even simpler structure, with only a Info.plist inside. Info.plist is read by the system to see what kinds of device it states to support by pid and vid. This Kext is loaded so that the default SCSI Kext provided by macOS will not load for STLink which prevents libusb from attaching and that’s all.
The incompatibility comes from the API change in 10.11. The usb stack was changed with a new name. As a result, it is ideal to provide a Kext for newer systems, changes the name of its dependency. Would not be so hard to do because the atmel Kext for newer systems provides a good reference.

In theory the new codeless Kext works from 10.11 to 10.15, with SIP disabled on 10.14 and 10.15. 

There is indeed a depreciation of Kexts coming, while in my view, as long as Apple continues using Kexts for their internal drivers, a codeless Kext will survive for a long time.

If someone feels happy to test a new Kext, I would like to make one. If it indeed works, the support prolongs, otherwise leaving a note in the documentation stating that it is not supported while some of them may work without a Kext would be a solution.

**Comment by Nightwalker-87** [comment]
I have the possibility to install the kext in an 10.13 and 10.14 VM. I suppose you are on Catalina. So at least the kext install and integration could be tested. As mentioned before it would still be helpful to have someone to do additional testing with a STlink-v1 programmer.

**Comment by chenguokai** [comment]
I am currently on Mojave 10.14 due to 32 bit support. Should not be a problem since codeless kexts barely need changes.

**Comment by Nightwalker-87** [comment]
@chenguokai: Would you mind to look into this? I am currently focussing on finalising the windows binary distribution topic and travis test-build impprovements, but can do some tests on 10.13 VM later on if useful.

**Comment by chenguokai** [comment]
> Would you mind to look into this?

I am not quite sure about “look into”. If there are users who feel happy to do some test, I will surely provide essential instructions. I cannot test myself because I do not have a ST-Link v1, no purchase available too.

**Comment by Nightwalker-87** [comment]
If I get to know what has to be changed for newer macOS versions specifically, based on a copy-paste-kext, I would take action myself.

**Comment by chenguokai** [comment]
A codeless `kext` has the following structure:

KEXTNAME.kext
....Contents
........Info.plist

Info.plist is either in binary or xml form. In our case, no binary form kexts have been found.

The change is caused by the removal of `IOUSBDevice` (previously defined in `IOKitPeraonalities`/`DeviceDriver`)

`IOUSBDevice` occurrences should be replaced by `IOUSBinterface` like the one in [https://www.avrfreaks.net/sites/default/files/forum_attachments/AtmelICE-kext-for-High-Sierra.zip](https://www.avrfreaks.net/sites/default/files/forum_attachments/AtmelICE-kext-for-High-Sierra.zip)

If `_CodeSignature` is presented in the kext template that you need to remove it (if signing is applicable, redo the signing is the best practice), since coming modifications break the signature.

`idProduct` and `idVendor` should be adjusted to what ST-Link v1 reports (can be found in older kexts)

`com.apple.kpi.kern` in `OSBundleLibraries`  seems to be redundant.

Other attributes, if different, should obey newer conventions presented in the Atmel's implementation.

**Comment by Nightwalker-87** [comment]
So it's time for this one then...

**Comment by Nightwalker-87** [comment]
I found this interesting Link: https://visserslatijn.wordpress.com/2019/01/20/upgrade-st-link-v1-to-v2/ We may add that to our project documentation.

Additionally I'd suggest to drop unsupported macOS 10.6 to 10.12 in the kext and thus give it another maintenance by ensuring it to run on 10.13 - 10.15 (with a :heart: for a very small mac-usergroup).

**Comment by chenguokai** [comment]
Great hack👏
Quite agree that we drop some old hardware-old OS combination support.

**Comment by Nightwalker-87** [comment]
Having noticed there is an old xcode project file in the kext-driver zip-file, led me to the idea to import that into xcode 11.3.1, because I think it is much easier to handle and edit all settings from there. The project settings and parameters should now be compatible with xcode 11 and later with updates and guided clean-up.

I've created targets for 10.13 to 10.15, but need to know exactly how to set the `CFBundleIdentifier` (I think this needs to be `com.apple.kpi.iokit`) and it's related settings for each of the mentioned versions. The code signing identity is now set to `Sign to Run Locally`, so I hope it'll work this way. However some assistance would be helpful. I've had a quick look into the AtmelICE-kext, but have not spent much time on it yet.

**Comment by chenguokai** [comment]
> I think this needs to be com.apple.kpi.iokit

I think so, too :-)

**Comment by Nightwalker-87** [comment]
I still face this error: `error: Build input file cannot be found: '/$USER_PATH$/stlink_shield/OptimizationProfiles/stlink_shield.profdata' (in target 'stlink_shield_10.15' from project 'stlink_shield')` This file is obviously missing, but it was not present before either... It is probably something Xcode-specific. How can it be generated?
